### ISSUE TITLE
Test Wax tasks to generate pages w/one csv

### ISSUE THREAD

**Issue by ejklein** [visualizingthefuture/examples-repository#45] opened 2020-06-12 18:06 UTC
Changes will be made in branch: wax_dev

- [x] Edit _data contents to 1) metadata file (csv) and 2) image folder/directory
- [x] Regenerate _datavis and _datasets files using wax tasks (removing existing .md files first)
- [x] Edit/Update config file
- [x] See if tasks work and successfully generate pages in _datavis and _datasets

**Comment by zoews** [comment] 2020-06-19 17:05
Checking in re: CSVs - have we confirmed that we can go ahead with one CSV as opposed to two CSVs (one per collection)? I just wanted to double-check - if we can, it makes the process of handling search much easier too, as we can render the index and search fields directly from the CSV as per #32 !

**Comment by ejklein** [comment] 2020-06-19 17:33
I haven't confirmed it yet -- Angela and I set up Git/GitHub Desktop and Ruby for my comp this morning, I'm starting the testing after this meeting ends! I think we should be able to, and agreed, will be much much easier!

**Comment by amzoss** [comment] 2020-07-24 23:49
Closing because this process works for one csv and we don't necessarily need to combine metadata from multiple collections. Each collection might have different metadata fields, so I think it's probably okay to stick with the normal wax model of separate .csv metadata files for each collection.

**Closed by amzoss** 2020-07-24 23:49 UTC
Labels: backend, metadata
